version: '3.8'

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v22.2
    command: start-single-node --insecure
    ports:
      # postgres
      - 26257:26257
      # ui
      - 8081:8080
    volumes:
      - './docker/cockroach/data:/cockroach/cockroach-data'
  cockroach-migrate:
    image: cockroachdb/cockroach:latest-v22.2
    command: sql --insecure --url "postgresql://root@cockroach:26257/?sslmode=disable" --execute "CREATE DATABASE IF NOT EXISTS hydra; CREATE DATABASE IF NOT EXISTS kratos;"
    restart: on-failure
    depends_on:
      - cockroach

  kratos:
    image: oryd/kratos:v0.13.0
    depends_on:
      - hydra
      - mailslurper
      - kratos-migrate
    ports:
      - '4000:4433' # public
    command: serve -c /etc/config/kratos/config.yml --dev --watch-courier
    env_file:
      - ./docker/kratos/config/.env
    volumes:
      - type: bind
        source: ./docker/kratos/config
        target: /etc/config/kratos
    restart: on-failure
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=cockroach://root@cockroach:26257/kratos?sslmode=disable
    volumes:
      - type: bind
        source: ./docker/kratos/config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/config.yml migrate sql -e --yes
    restart: on-failure
    depends_on:
      - cockroach-migrate

  hydra:
    image: oryd/hydra:v2.1.1
    ports:
      - '5444:4444' # public
      - '5445:4445' # admin
      - '5446:5446' # token client (hydra perform authorization-code)
    command: serve -c /etc/config/hydra/config.yml all --dev
    volumes:
      - type: bind
        source: ./docker/hydra/config
        target: /etc/config/hydra
    depends_on:
      - hydra-migrate
    restart: on-failure
  hydra-migrate:
    image: oryd/hydra:v2.1.1
    environment:
      - DSN=cockroach://root@cockroach:26257/hydra?sslmode=disable
    command: migrate -c /etc/config/hydra/config.yml sql -e --yes
    volumes:
      - type: bind
        source: ./docker/hydra/config
        target: /etc/config/hydra
    restart: on-failure
    depends_on:
      - cockroach-migrate
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436' # website
      - '4437:4437' # API
