version: '3.8'

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v22.2
    command: start-single-node --insecure
    ports:
      # postgres
      - 26257:26257
      # ui
      - 8081:8080
    volumes:
      - './docker/cochroach/data:/cockroach/cockroach-data'
