version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: waldo
      POSTGRES_PASSWORD: waldo
      POSTGRES_DB: waldo
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
