serve:
  cookies:
    same_site_mode: Strict

dsn: 'cockroach://root@cockroach:26257/hydra?sslmode=disable'

log:
  leak_sensitive_values: true
urls:
  self:
    issuer: http://127.0.0.1:5444
  consent: http://127.0.0.1:3001/consent
  login: http://127.0.0.1:4000/self-service/login/browser
  logout: http://127.0.0.1:4000/self-service/logout/browser

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
