serve:
  cookies:
    same_site_mode: Strict

dsn: 'cockroach://root@cockroach:26257/hydra?sslmode=disable'

log:
  level: debug
  format: text
  leak_sensitive_values: true
urls:
  self:
    issuer: http://127.0.0.1:5444
  consent: http://127.0.0.1:3001/consent
  login: http://127.0.0.1:3001/oauth
  logout: http://127.0.0.1:4000/self-service/logout/browser #Todo fix this stuff

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
