version: v0.11.0
dev: true
dsn: 'cockroach://root@cockroach:26257/hydra?sslmode=disable'
cookies:
  same_site: Strict
serve:
  public:
    base_url: http://127.0.0.1:4000/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:3001
  allowed_return_urls:
    - http://127.0.0.1:3001

  methods:
    password:
      config:
        haveibeenpwned_enabled: false
        min_password_length: 6
        identifier_similarity_check_enabled: false
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      enabled: true #enable openid connect methods
      config:
        providers:
          #github#
          - id: github
            label: 'GitHub'
            provider: github
            mapper_url: file:///etc/config/kratos/github.jsonnet
            scope:
              - user:email
            #google#
          - id: google
            label: 'Google'
            provider: google
            mapper_url: file:///etc/config/kratos/google.jsonnet
            issuer_url: https://accounts.google.com
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://oauth2.googleapis.com/token
            scope:
              - openid
              - email
              - profile
            #discord#
          - id: discord
            provider: discord
            label: 'Discord'
            mapper_url: file:///etc/config/kratos/discord.jsonnet
            auth_url: https://discord.com/oauth2/authorize
            token_url: https://discord.com/api/oauth2/token
            scope:
              - identify
              - email
            #twitch#
          - id: twitch
            label: 'Twitch'
            provider: generic
            issuer_url: https://id.twitch.tv/oauth2
            mapper_url: file:///etc/config/kratos/twitch.jsonnet
            scope:
              - openid
              - user:read:email # required for email and email_verified claims in the near future
            requested_claims: # explicitly request email and email_verified claims because twitch doesn't add them by default
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
            #battlenet#
          - id: battlenet
            label: Battle.net
            provider: generic
            auth_url: https://oauth.battle.net/authorize
            token_url: https://oauth.battle.net/token
            issuer_url: https://oauth.battle.net
            mapper_url: file:///etc/config/kratos/battlenet.jsonnet
            scope:
              - openid
  flows:
    error:
      ui_url: http://127.0.0.1:3001/error

    settings:
      ui_url: http://127.0.0.1:3001/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:3001/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:3001/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:3001

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:3001/login

    login:
      ui_url: http://127.0.0.1:3001/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:3001/registration
      after:
        password:
          hooks:
            - hook: session
        oidc: #autologin after register
          hooks:
            - hook: session

oauth2_provider:
  url: http://hydra:4445

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
