# This is a workflow used to test the integration tests in GitHub actions.
# DO NOT COMMIT TO MAIN

name: Integration test

on:
  push:
    branches:
      - feat/integration-tests

jobs:
  tests:
    name: Integration Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      # See https://stackoverflow.com/questions/73648218/github-action-setup-secure-cockroachdb
      - name: Start a single CockroachDB instance (cockroachdb/cockroach:latest-v22.2) with docker
        run: |
          docker pull cockroachdb/cockroach:latest-v22.2
          docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:latest-v22.2 start-single-node --insecure
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 26257

      - name: Build server
        run: yarn turbo run build --filter=web...

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://root@localhost:26257?sslmode=disable
        run: |
          yarn turbo run db:push

      - name: Run tests
        env:
          DATABASE_URL: postgresql://root@localhost:26257?sslmode=disable
          WALDO_URI: http://localhost:3000
          DISABLE_VERIFY_AUTH: '1'
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: myauthsecret
          CLOUDFLARE_TURNSTILE_SECRET: 1x0000000000000000000000000000000AA
          NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY: 1x00000000000000000000AA
        run: |
          # Copy configuration
          cp apps/web/.env.example apps/web/.env

          # Start server
          node apps/web/.next/standalone/apps/web/server.js &
          wait-for-it -h localhost -p 3000 -t 90

          # Run integration tests
          yarn workspace tests jest
